

const ADDITIVES = {
  "E330": "A preservative and flavoring agent that can cause gastrointestinal issues and tooth erosion when consumed excessively.",
  "E322": "An emulsifier derived from soy or egg, lecithins can cause allergic reactions and gastrointestinal distress.",
  "E322i": "An emulsifier often from soy, lecithin can trigger allergic reactions and digestive issues.",
  "E500": "A raising agent that can cause digestive upset and electrolyte imbalances.",
  "E415": "A thickening agent that can cause bloating, gas, and digestive discomfort.",
  "E471": "Emulsifiers that may cause digestive issues and contribute to unhealthy weight gain.",
  "E500ii": "A raising agent that can cause digestive problems and sodium overload.",
  "E412": "A thickening agent that may cause bloating, gas, and abdominal pain.",
  "E202": "A preservative linked to allergic reactions, skin irritations, and potential DNA damage.",
  "E450": "Stabilizers that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E407": "A thickening agent associated with inflammation, digestive issues, and potential carcinogenic effects.",
  "E440": "Thickeners that may cause bloating and digestive discomfort.",
  "E250": "A preservative linked to increased cancer risk, especially colorectal cancer, and potential cardiovascular issues.",
  "E300": "A preservative and antioxidant that can cause digestive issues and potential kidney stone formation.",
  "E14XX": "Stabilizers and thickeners that can cause digestive distress and allergic reactions.",
  "E331": "Acidity regulators that may cause digestive issues and affect kidney function.",
  "E270": "An acidity regulator that can cause digestive discomfort and potential lactic acidosis in high amounts.",
  "E129": "A coloring agent linked to hyperactivity in children, allergies, and potential carcinogenic effects.",
  "E150c": "A coloring agent that may cause gastrointestinal issues and has potential carcinogenic properties.",
  "E102": "A coloring agent linked to hyperactivity in children, allergies, and potential carcinogenic effects.",
  "E422": "A humectant that can cause digestive distress, including bloating and diarrhea.",
  "E133": "A coloring agent linked to hyperactivity in children and allergic reactions.",
  "E211": "A preservative associated with hyperactivity, allergic reactions, and potential carcinogenic effects when combined with vitamin C.",
  "E341": "Stabilizers that can cause digestive issues and disrupt calcium and phosphate balance in the body.",
  "E428": "A gelling agent derived from animal products that can cause allergic reactions and digestive issues.",
  "E410": "A thickening agent that may cause digestive issues like bloating and gas.",
  "E414": "A thickening agent that can cause digestive issues like bloating and gas.",
  "E621": "A flavor enhancer linked to headaches, nausea, and other symptoms of \"Chinese Restaurant Syndrome.\"",
  "E450i": "A stabilizer that may cause kidney damage and calcium imbalance, affecting bone health.",
  "E160a": "A coloring agent where high doses of synthetic carotene can increase lung cancer risk in smokers.",
  "E955": "A sweetener linked to digestive issues, altered gut microbiota, and potential metabolic disturbances.",
  "E110": "A coloring agent associated with hyperactivity in children, allergies, and potential carcinogenic effects.",
  "E296": "An acidity regulator that can cause digestive discomfort and throat irritation.",
  "E466": "A thickener that can cause digestive issues and potential allergenic reactions.",
  "E503": "A raising agent that can cause digestive issues and respiratory irritation.",
  "E160b": "A coloring agent that can cause allergic reactions and potential digestive issues.",
  "E160c": "A coloring agent that can cause allergic reactions and digestive discomfort.",
  "E420": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E341i": "A stabilizer that can cause digestive issues and calcium-phosphate imbalance.",
  "E950": "A sweetener linked to potential carcinogenic effects and metabolic disturbances.",
  "E301": "A preservative and antioxidant that can cause digestive issues and kidney stones.",
  "E262": "Acidity regulators that may cause digestive issues and sodium overload.",
  "E316": "A preservative that can cause digestive issues and potential allergenic reactions.",
  "E903": "A glazing agent that may cause digestive issues and potential allergenic reactions.",
  "E282": "A preservative linked to allergic reactions, migraines, and potential gastrointestinal issues.",
  "E171": "A coloring agent linked to potential carcinogenic effects and digestive issues.",
  "E200": "A preservative linked to allergic reactions, skin irritations, and potential DNA damage.",
  "E452": "Stabilizers that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E160ai": "A coloring agent where high doses of synthetic beta-carotene can increase lung cancer risk in smokers.",
  "E100": "A coloring agent where synthetic curcumin can cause digestive issues and potential liver toxicity.",
  "E460": "A thickener that can cause digestive issues like bloating and gas.",
  "E306": "An antioxidant where synthetic tocopherols can cause digestive issues and potential allergic reactions.",
  "E631": "A flavor enhancer linked to allergies, digestive issues, and potential gout flare-ups.",
  "E481": "An emulsifier that can cause digestive issues and potential allergenic reactions.",
  "E503ii": "A raising agent that can cause digestive issues and respiratory irritation.",
  "E627": "A flavor enhancer linked to allergies, digestive issues, and potential gout flare-ups.",
  "E472e": "Emulsifiers that may cause digestive issues and contribute to unhealthy weight gain.",
  "E1400": "A thickener that can cause digestive issues and potential allergenic reactions.",
  "E451": "Stabilizers that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E120": "A coloring agent derived from insects that can cause allergic reactions and digestive issues.",
  "E340": "Stabilizers that can cause digestive issues and affect kidney function.",
  "E392": "Antioxidants that can cause allergic reactions and digestive discomfort.",
  "E951": "A sweetener linked to headaches, mood disorders, and potential carcinogenic effects.",
  "E385": "A sequestrant that can cause digestive issues, kidney damage, and deplete essential minerals.",
  "E401": "A thickener that can cause digestive issues and potential allergenic reactions.",
  "E260": "An acidity regulator that can cause digestive discomfort and throat irritation.",
  "E223": "A preservative linked to allergic reactions, respiratory issues, and potential carcinogenic effects.",
  "E321": "An antioxidant linked to cancer, liver damage, and reproductive issues.",
  "E435": "An emulsifier that can cause digestive issues and potential allergenic reactions.",
  "E476": "An emulsifier that can cause digestive issues and potential allergenic reactions.",
  "E541": "A stabilizer linked to Alzheimer's disease and bone health issues.",
  "E338": "An acidity regulator linked to kidney issues, bone loss, and dental erosion.",
  "E262ii": "An acidity regulator that may cause digestive issues and sodium overload.",
  "E339ii": "A stabilizer that can cause digestive issues and affect kidney function.",
  "E150a": "A coloring agent linked to gastrointestinal issues and potential carcinogenic properties.",
  "E127": "A coloring agent linked to hyperactivity, thyroid issues, and potential carcinogenic effects.",
  "E290": "A propellant where excessive inhalation can cause respiratory issues and dizziness.",
  "E433": "An emulsifier that can cause digestive issues and potential allergenic reactions.",
  "E252": "A preservative linked to cancer, digestive issues, and methemoglobinemia.",
  "E965": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E235": "A preservative that can cause allergic reactions and potential digestive issues.",
  "E960": "A sweetener linked to digestive issues and potential metabolic disturbances.",
  "E220": "A preservative linked to respiratory issues, allergic reactions, and potential DNA damage.",
  "E406": "A gelling agent that can cause digestive issues like bloating and gas.",
  "E326": "A preservative that may cause digestive issues and electrolyte imbalances.",
  "E132": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E150d": "A coloring agent linked to gastrointestinal issues and potential carcinogenic properties.",
  "E340ii": "A stabilizer that can cause digestive issues and affect kidney function.",
  "E418": "A gelling agent that may cause digestive issues like bloating and gas.",
  "E325": "A preservative that may cause digestive issues and sodium overload.",
  "E461": "A thickener that can cause digestive issues and potential allergenic reactions.",
  "E163": "Coloring agents that processed anthocyanins can cause allergic reactions and digestive discomfort.",
  "E320": "An antioxidant linked to cancer, liver damage, and reproductive issues.",
  "E334": "An acidity regulator where high amounts can cause digestive discomfort and acid-base imbalance.",
  "E297": "An acidity regulator that can cause digestive discomfort and potential kidney damage.",
  "E339": "Stabilizers that can cause digestive issues and affect kidney function.",
  "E160": "Coloring agents where synthetic carotenoids can cause lung issues and potential toxicity.",
  "E319": "An antioxidant linked to cancer, liver damage, and vision disturbances.",
  "E1520": "A humectant linked to kidney issues, respiratory problems, and potential toxicity.",
  "E170": "A stabilizer where high amounts can cause digestive discomfort and kidney stones.",
  "E901": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E224": "A preservative linked to allergic reactions, respiratory issues, and potential carcinogenic effects.",
  "E445": "Emulsifiers that can cause digestive issues and potential allergenic reactions.",
  "E327": "A stabilizer that may cause digestive issues and calcium overload.",
  "E460ii": "A thickener that can cause digestive issues like bloating and gas.",
  "E150": "A coloring agent linked to gastrointestinal issues and potential carcinogenic properties.",
  "E101": "A coloring agent where high synthetic doses can cause digestive issues and urine discoloration.",
  "E500i": "A raising agent that may cause digestive upset and electrolyte imbalances.",
  "E501": "A raising agent that can cause digestive issues and potassium overload.",
  "E452i": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E281": "A preservative linked to allergic reactions, migraines, and potential gastrointestinal issues.",
  "E904": "A glazing agent that may cause digestive issues and potential allergenic reactions.",
  "E212": "A preservative associated with hyperactivity, allergic reactions, and potential carcinogenic effects when combined with vitamin C.",
  "E336": "Acidity regulators that may cause digestive issues and affect potassium levels.",
  "E570": "Processed fatty acids that may cause digestive issues and unhealthy weight gain.",
  "E551": "An anti-caking agent where inhalation can cause respiratory issues; ingestion in large amounts may affect digestion.",
  "E968": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E491": "An emulsifier that can cause digestive issues and potential allergenic reactions.",
  "E262i": "An acidity regulator that may cause digestive issues and sodium overload.",
  "E170i": "A stabilizer where high amounts can cause digestive discomfort and kidney stones.",
  "E162": "A coloring agent where processed beetroot red can cause allergic reactions and digestive discomfort.",
  "E516": "A stabilizer that may cause digestive issues and calcium overload.",
  "E1200": "A bulking agent linked to digestive issues like bloating, gas, and diarrhea.",
  "E452vi": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E331iii": "An acidity regulator that may cause digestive issues and affect kidney function.",
  "E509": "A firming agent that can cause digestive issues and calcium overload.",
  "E475": "Emulsifiers that can cause digestive issues and potential allergenic reactions.",
  "E222": "A preservative linked to allergic reactions, respiratory issues, and potential carcinogenic effects.",
  "E161b": "A coloring agent where high doses may cause digestive discomfort and skin discoloration.",
  "E575": "An acidity regulator that may cause digestive issues and potential allergic reactions.",
  "E1510": "A solvent where excessive consumption can cause liver damage, addiction, and impaired brain function.",
  "E304": "Antioxidants that can cause digestive issues and potential allergic reactions.",
  "E141": "Coloring agents that may cause digestive issues and potential copper toxicity.",
  "E464": "A thickener that can cause digestive issues and potential allergenic reactions.",
  "E967": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E336i": "An acidity regulator that may cause digestive issues and affect potassium levels.",
  "E1103": "An enzyme that can cause digestive issues and potential allergic reactions.",
  "E341ii": "A stabilizer that can cause digestive issues and calcium-phosphate imbalance.",
  "E635": "A flavor enhancer linked to allergies, digestive issues, and potential gout flare-ups.",
  "E965ii": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E251": "A preservative linked to increased cancer risk, especially colorectal cancer, and potential cardiovascular issues.",
  "E517": "A firming agent that can cause digestive issues and potential allergic reactions.",
  "E153": "A coloring agent where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E101i": "A coloring agent where high synthetic doses can cause digestive issues and urine discoloration.",
  "E524": "A pH regulator that can cause severe digestive and respiratory tract irritation.",
  "E1100": "An enzyme that can cause digestive issues and potential allergic reactions.",
  "E572": "An anti-caking agent that may cause digestive issues and magnesium imbalance.",
  "E905": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E920": "An amino acid derived from animal products that can cause allergic reactions and digestive issues.",
  "E460i": "A thickener that can cause digestive issues like bloating and gas.",
  "E954": "Sweeteners linked to potential carcinogenic effects and digestive issues.",
  "E450iii": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E1105": "An enzyme that can cause allergic reactions and digestive issues.",
  "E472b": "Emulsifiers that may cause digestive issues and unhealthy weight gain.",
  "E1442": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E502": "Raising agents that may cause digestive upset and electrolyte imbalances.",
  "E1422": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E501i": "A raising agent that can cause digestive issues and potassium overload.",
  "E307": "An antioxidant where synthetic alpha-tocopherol can cause digestive issues and potential allergic reactions.",
  "E905a": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E953": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E417": "A thickener that can cause digestive issues like bloating and gas.",
  "E420ii": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E333": "Acidity regulators that may cause digestive issues and calcium overload.",
  "E521": "A stabilizer linked to Alzheimer’s disease and bone health issues.",
  "E552": "An anti-caking agent where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E503i": "A raising agent that can cause digestive issues and respiratory irritation.",
  "E579": "A color fixative where excessive intake can lead to digestive discomfort and iron overload.",
  "E304i": "A synthetic antioxidant that can cause digestive issues and potential allergic reactions.",
  "E339iii": "A stabilizer that can cause digestive issues and affect kidney function.",
  "E492": "An emulsifier that can cause digestive issues and potential allergenic reactions.",
  "E421": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E442": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E407a": "A thickener linked to inflammation, digestive issues, and potential carcinogenic effects.",
  "E900": "An anti-foaming agent linked to digestive issues and potential allergenic reactions.",
  "E952": "Sweeteners linked to potential carcinogenic effects and metabolic disturbances.",
  "E160e": "A synthetic coloring agent that can cause lung issues and potential toxicity.",
  "E172": "Coloring agents where excessive intake can lead to digestive discomfort and iron overload.",
  "E451i": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E473": "Emulsifiers that may cause digestive issues and contribute to unhealthy weight gain.",
  "E405": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E927": "Dough conditioners linked to respiratory issues and potential carcinogenic effects.",
  "E221": "A preservative linked to allergic reactions, respiratory issues, and potential carcinogenic effects.",
  "E332": "Acidity regulators that may cause digestive issues and affect kidney function.",
  "E310": "An antioxidant linked to potential carcinogenic effects and digestive issues.",
  "E900a": "An anti-foaming agent linked to digestive issues and potential allergenic reactions.",
  "E261": "An acidity regulator that may cause digestive issues and affect potassium levels.",
  "E131": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E263": "A stabilizer that may cause digestive issues and calcium overload.",
  "E477": "Emulsifiers that may cause digestive issues and unhealthy weight gain.",
  "E340i": "A stabilizer that can cause digestive issues and affect kidney function.",
  "E930": "A flour treatment agent that may cause digestive issues and oxidative stress.",
  "E554": "A stabilizer linked to Alzheimer’s disease and bone health issues.",
  "E927a": "A dough conditioner linked to respiratory issues and potential carcinogenic effects.",
  "E355": "An acidity regulator that can cause digestive discomfort and potential kidney damage.",
  "E472c": "Emulsifiers that may cause digestive issues and contribute to unhealthy weight gain.",
  "E413": "A thickener that can cause digestive issues like bloating and gas.",
  "E470b": "Anti-caking agents that may cause digestive issues and magnesium imbalance.",
  "E553": "Anti-caking agents where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E210": "A preservative linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E508": "A stabilizer that can cause digestive issues and potassium overload.",
  "E535": "An anti-caking agent linked to potential cyanide toxicity and digestive issues.",
  "E510": "A flavor enhancer that can cause digestive issues and respiratory irritation.",
  "E350": "Stabilizers that may cause digestive issues and sodium overload.",
  "E501ii": "A raising agent that can cause digestive issues and potassium overload.",
  "E553b": "An anti-caking agent where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E341iii": "A stabilizer that can cause digestive issues and calcium-phosphate imbalance.",
  "E122": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E1104": "An enzyme that can cause digestive issues and potential allergic reactions.",
  "E140": "Coloring agents that may cause digestive issues and potential copper toxicity.",
  "E1101": "An enzyme that can cause digestive issues and potential allergic reactions.",
  "E520": "A stabilizer linked to Alzheimer’s disease and bone health issues.",
  "E124": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E315": "A synthetic antioxidant that can cause digestive issues and potential allergic reactions.",
  "E444": "An emulsifier that can cause digestive issues and potential allergenic reactions.",
  "E164": "A coloring agent where processed saffron can cause allergic reactions and digestive discomfort.",
  "E363": "An acidity regulator that may cause digestive discomfort and throat irritation.",
  "E160bii": "A coloring agent that can cause allergic reactions and potential digestive issues.",
  "E443": "An emulsifier linked to thyroid issues, memory loss, and skin problems.",
  "E343": "Stabilizers that may cause digestive issues and magnesium imbalance.",
  "E941": "A propellant where excessive inhalation can cause respiratory issues and dizziness.",
  "E472a": "Emulsifiers that may cause digestive issues and contribute to unhealthy weight gain.",
  "E425": "A gelling agent that can cause digestive issues like bloating and gas.",
  "E141ii": "Coloring agents that may cause digestive issues and potential copper toxicity.",
  "E234": "A preservative that can cause allergic reactions and digestive issues.",
  "E640": "Flavor enhancers that may cause digestive issues and metabolic imbalances.",
  "E150b": "A coloring agent linked to gastrointestinal issues and potential carcinogenic properties.",
  "E340iii": "A stabilizer that can cause digestive issues and affect kidney function.",
  "E280": "A preservative linked to allergic reactions, migraines, and potential gastrointestinal issues. Potassium iodide: A fortifying agent that may cause thyroid dysfunction and allergic reactions.",
  "E331i": "An acidity regulator that may cause digestive issues and sodium overload.",
  "E924a": "A flour treatment agent linked to cancer and kidney damage.",
  "E160aii": "Coloring agents where high doses of synthetic carotenes can increase lung cancer risk in smokers.",
  "E343i": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E504": "Stabilizers that may cause digestive issues and magnesium imbalance.",
  "E960a": "Sweeteners linked to digestive issues and potential metabolic disturbances.",
  "E307b": "A synthetic antioxidant that can cause digestive issues and potential allergic reactions.",
  "E160d": "A coloring agent where high doses of synthetic lycopene can cause digestive issues and potential toxicity.",
  "E141i": "Coloring agents that may cause digestive issues and potential copper toxicity. Amino acids: Flavor enhancers where processed amino acids can cause digestive issues and metabolic imbalances.",
  "E332ii": "An acidity regulator that may cause digestive issues and affect kidney function.",
  "E640i": "A flavor enhancer that may cause digestive issues and metabolic imbalances.",
  "E1519": "A solvent that can cause respiratory issues and potential toxicity.",
  "E1450": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E916": "A fortifying agent that may cause thyroid dysfunction and allergic reactions.",
  "E641": "An amino acid where excessive intake may cause digestive discomfort and metabolic imbalances.",
  "E482": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E175": "A coloring agent where ingestion can cause digestive issues and potential toxicity.",
  "E1505": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E1414": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E1412": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E942": "A propellant where excessive inhalation can cause respiratory issues and dizziness.",
  "E525": "A pH regulator that can cause severe digestive and respiratory tract irritation.",
  "E472": "Emulsifiers that may cause digestive issues and unhealthy weight gain.",
  "E585": "A color fixative where excessive intake can lead to digestive discomfort and iron overload.",
  "E140i": "Coloring agents that may cause digestive issues and potential copper toxicity.",
  "E404": "A gelling agent that can cause digestive issues and potential allergic reactions.",
  "E416": "A thickener that can cause digestive issues like bloating and gas.",
  "E961": "A sweetener linked to potential carcinogenic effects and metabolic disturbances.",
  "E350ii": "A stabilizer that may cause digestive issues and sodium overload.",
  "E104": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E339i": "A stabilizer that can cause digestive issues and affect kidney function.",
  "E1420": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E1210": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E487": "An emulsifier linked to digestive issues and potential toxicity.",
  "E218": "A preservative linked to allergic reactions and potential hormonal disruptions.",
  "E1518": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E140ii": "Coloring agents that may cause digestive issues and potential copper toxicity.",
  "E216": "A preservative linked to allergic reactions and potential hormonal disruptions.",
  "E1521": "An emulsifier linked to digestive issues and potential allergic reactions.",
  "E928": "A flour treatment agent that can cause skin and respiratory irritation; potential carcinogenic effects.",
  "E425i": "A gelling agent that can cause digestive issues like bloating and gas.",
  "E440a": "A thickener where processed pectins may cause bloating and digestive discomfort.",
  "E905b": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E333iii": "A stabilizer that may cause digestive issues and calcium overload.",
  "E440ii": "A thickener where processed pectins may cause bloating and digestive discomfort.",
  "E470a": "Anti-caking agents where processed salts may cause digestive issues and metabolic imbalances.",
  "E463": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E242": "A preservative linked to potential carcinogenic effects and respiratory issues.",
  "E949": "A propellant where excessive inhalation can cause respiratory issues and dizziness.",
  "E142": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E576": "A stabilizer that may cause digestive issues and sodium overload.",
  "E143": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E1201": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E536": "An anti-caking agent linked to potential cyanide toxicity and digestive issues.",
  "E620": "A flavor enhancer where excessive intake can cause headaches, digestive issues, and potential neurotoxicity.",
  "E1404": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E420i": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E511": "A firming agent that may cause digestive issues and magnesium imbalance.",
  "E400": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E329": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E342": "A stabilizer that can cause digestive issues and potential allergic reactions.",
  "E927b": "A dough conditioner linked to respiratory issues and potential carcinogenic effects.",
  "E151": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E1503": "A glazing agent that can cause digestive issues and potential allergic reactions.",
  "E432": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E160bi": "A coloring agent that can cause allergic reactions and potential digestive issues.",
  "E228": "A preservative linked to allergic reactions, respiratory issues, and potential carcinogenic effects.",
  "E331ii": "An acidity regulator that may cause digestive issues and sodium overload.",
  "E468": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E999": "An emulsifier linked to digestive issues and potential allergenic reactions.",
  "E917": "A fortifying agent that may cause thyroid dysfunction and allergic reactions.",
  "E966": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E902": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E526": "A firming agent that can cause severe digestive and respiratory tract irritation.",
  "E962": "A sweetener linked to potential carcinogenic effects and metabolic disturbances.",
  "E172ii": "A coloring agent where excessive intake can lead to digestive discomfort and iron overload.",
  "E504i": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E450ii": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E123": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E450v": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E514": "A stabilizer that may cause digestive issues and sodium overload.",
  "E944": "A propellant where inhalation can cause respiratory issues and dizziness.",
  "E1102": "An enzyme that can cause digestive issues and potential allergic reactions.",
  "E343ii": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E155": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E1202": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E249": "A preservative linked to increased cancer risk, especially colorectal cancer, and potential cardiovascular issues.",
  "E957": "A sweetener that may cause digestive issues and potential allergic reactions.",
  "E350i": "A stabilizer that may cause digestive issues and sodium overload. de:Gärungskohlensäure: A carbonation agent that may cause digestive issues and gas build-up.",
  "E914": "A glazing agent linked to digestive issues and potential allergic reactions.",
  "E324": "An antioxidant linked to potential carcinogenic effects and digestive issues.",
  "E943b": "A propellant where inhalation can cause respiratory issues and dizziness.",
  "E436": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E959": "A sweetener linked to potential carcinogenic effects and metabolic disturbances.",
  "E203": "A preservative that may cause allergic reactions and potential digestive issues.",
  "E1440": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E943a": "A propellant where inhalation can cause respiratory issues and dizziness.",
  "E173": "A coloring agent linked to Alzheimer’s disease and bone health issues.",
  "E530": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E451ii": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E440i": "A thickener where processed pectins may cause bloating and digestive discomfort.",
  "E470": "Anti-caking agents where processed salts may cause digestive issues and metabolic imbalances.",
  "E905c": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E636": "A flavor enhancer linked to digestive issues and potential allergic reactions.",
  "E515": "A stabilizer that may cause digestive issues and potassium overload.",
  "E555": "A stabilizer linked to Alzheimer’s disease and bone health issues.",
  "E507": "A pH regulator that can cause severe digestive and respiratory tract irritation.",
  "E490": "A humectant linked to kidney issues, respiratory problems, and potential toxicity.",
  "E1203": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E161h": "A coloring agent where high doses may cause digestive discomfort and skin discoloration.",
  "E913": "A glazing agent that may cause allergic reactions and potential digestive issues.",
  "E307c": "A synthetic antioxidant that can cause digestive issues and potential allergic reactions.",
  "E472d": "Emulsifiers that may cause digestive issues and unhealthy weight gain.",
  "E637": "A flavor enhancer linked to digestive issues and potential allergic reactions.",
  "E317": "A synthetic antioxidant that can cause digestive issues and potential allergic reactions.",
  "E243": "A preservative that can cause digestive issues and potential allergic reactions.",
  "E302": "A preservative and antioxidant that can cause digestive issues and kidney stones.",
  "E452ii": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E285": "A preservative linked to reproductive issues, digestive discomfort, and potential toxicity. .",
  "E905ci": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E514ii": "A stabilizer that may cause digestive issues and sodium overload.",
  "E386": "A sequestrant that can cause digestive issues and potential allergic reactions.",
  "E201": "A preservative linked to allergic reactions, skin irritations, and potential DNA damage.",
  "E1401": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E335": "An acidity regulator that may cause digestive issues and sodium overload.",
  "E336ii": "An acidity regulator that may cause digestive issues and affect potassium levels.",
  "E559": "A stabilizer linked to Alzheimer’s disease and bone health issues.",
  "E529": "A firming agent that can cause severe digestive and respiratory tract irritation.",
  "E160aiii": "A synthetic coloring agent where high doses can increase lung cancer risk in smokers.",
  "E174": "A coloring agent where ingestion can cause digestive issues and potential toxicity.",
  "E1001": "A fortifying agent where excessive intake can cause digestive discomfort and metabolic imbalances.",
  "E214": "A preservative linked to allergic reactions and potential hormonal disruptions.",
  "E963": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E365": "An acidity regulator that may cause digestive discomfort and throat irritation.",
  "E925": "A disinfectant where excessive exposure can cause respiratory and digestive issues.",
  "E160aiv": "A synthetic coloring agent where high doses can increase lung cancer risk in smokers.",
  "E403": "A gelling agent that can cause digestive issues and potential allergic reactions.",
  "E964": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E1405": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E470ai": "Anti-caking agents where processed salts may cause digestive issues and metabolic imbalances.",
  "E180": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E265": "A preservative linked to allergic reactions and potential DNA damage.",
  "E375": "A fortifying agent where excessive intake can cause digestive discomfort and liver issues.",
  "E523": "A stabilizer linked to Alzheimer’s disease and bone health issues. Isomaltose: A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E1421": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E101ii": "A coloring agent where high synthetic doses can cause digestive issues and urine discoloration.",
  "E948": "A propellant where excessive inhalation can cause respiratory issues and dizziness.",
  "E450vii": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E233": "A preservative linked to potential carcinogenic effects and liver damage.",
  "E462": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E1504": "A solvent linked to potential carcinogenic effects and respiratory irritation.",
  "E161g": "A coloring agent where high doses can cause digestive issues and potential toxicity.",
  "E402": "A gelling agent that can cause digestive issues and potential allergic reactions.",
  "E337": "An acidity regulator that may cause digestive issues and affect potassium levels.",
  "E958": "A sweetener linked to potential hormonal disruptions and high blood pressure.",
  "E541i": "A stabilizer linked to Alzheimer’s disease and bone health issues.",
  "E577": "A stabilizer that may cause digestive issues and potassium overload. de:Quellkohlensäure: A carbonation agent that may cause digestive issues and gas build-up.",
  "E650": "A fortifying agent where excessive intake can cause digestive discomfort and zinc toxicity.",
  "E266": "A preservative linked to allergic reactions and potential DNA damage.",
  "E494": "An emulsifier that can cause digestive issues and potential allergenic reactions.",
  "E1204": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E514i": "A stabilizer that may cause digestive issues and sodium overload.",
  "E152": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E630": "A flavor enhancer linked to allergies, digestive issues, and potential gout flare-ups.",
  "E539": "An anti-caking agent linked to potential cyanide toxicity and digestive issues.",
  "E639": "A flavor enhancer that can cause digestive issues and potential allergic reactions.",
  "E225": "A preservative linked to allergic reactions, respiratory issues, and potential carcinogenic effects.",
  "E965i": "A sweetener linked to digestive issues like bloating, gas, and diarrhea.",
  "E236": "A preservative linked to potential carcinogenic effects and digestive discomfort.",
  "E1000": "A fortifying agent where excessive intake can cause digestive discomfort and liver issues.",
  "E165": "A coloring agent where processed gardenia blue can cause allergic reactions and digestive discomfort.",
  "E425ii": "A thickener that can cause digestive issues like bloating and gas.",
  "E172i": "A coloring agent where excessive intake can lead to digestive discomfort and iron overload.",
  "E303": "A preservative and antioxidant where synthetic vitamin C can cause digestive issues and kidney stones.",
  "E311": "An antioxidant linked to potential carcinogenic effects and digestive issues.",
  "E219": "A preservative linked to allergic reactions and potential hormonal disruptions.",
  "E624": "A flavor enhancer linked to allergies, digestive issues, and potential neurotoxicity.",
  "E522": "A stabilizer linked to Alzheimer’s disease and bone health issues. Organic acids: Acidity regulators where excessive intake can cause digestive discomfort and acid-base imbalance.",
  "E504ii": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E905cii": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E353": "An acidity regulator that may cause digestive discomfort and acid-base imbalance.",
  "E469": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E441": "An emulsifier where processed fats may cause digestive issues and unhealthy weight gain.",
  "E457": "A stabilizer that can cause digestive issues and potential allergic reactions.",
  "E172iii": "A coloring agent where excessive intake can lead to digestive discomfort and iron overload.",
  "E130": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E550": "An anti-caking agent where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E161": "A coloring agent where high doses can cause digestive discomfort and potential toxicity.",
  "E558": "An anti-caking agent where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E230": "A preservative linked to potential carcinogenic effects and liver damage.",
  "E352": "A stabilizer that may cause digestive issues and calcium overload.",
  "E364": "An acidity regulator that can cause digestive issues and potential allergic reactions.",
  "E181": "A stabilizer where high doses can cause digestive discomfort and potential liver toxicity.",
  "E578": "A stabilizer where excessive intake can lead to digestive discomfort and calcium overload.",
  "E622": "A flavor enhancer linked to allergies, digestive issues, and potential neurotoxicity.",
  "E226": "A preservative linked to allergic reactions, respiratory issues, and potential carcinogenic effects.",
  "E411": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E125": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E921": "An amino acid derived from animal products that can cause allergic reactions and digestive issues.",
  "E381": "A fortifying agent where excessive intake can lead to digestive discomfort and iron overload.",
  "E307a": "A synthetic antioxidant that can cause digestive issues and potential allergic reactions.",
  "E161j": "A coloring agent where high doses can cause digestive issues and potential toxicity.",
  "E528": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E527": "A pH regulator that can cause severe digestive and respiratory tract irritation.",
  "E409": "A thickener that can cause digestive issues like bloating and gas.",
  "E626": "A flavor enhancer linked to allergies, digestive issues, and potential gout flare-ups.",
  "E380": "A sequestrant that can cause digestive issues and potential allergic reactions.",
  "E474": "Emulsifiers where processed fats may cause digestive issues and unhealthy weight gain.",
  "E500iii": "A raising agent that may cause digestive issues and sodium overload.",
  "E332i": "An acidity regulator that may cause digestive issues and affect kidney function.",
  "E908": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E309": "A synthetic antioxidant that can cause digestive issues and potential allergic reactions.",
  "E419": "A thickener that can cause digestive issues like bloating and gas.",
  "E391": "A preservative that may cause digestive discomfort and mineral deficiencies.",
  "E370": "A sequestrant that can cause digestive issues and potential allergic reactions.",
  "E1410": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E459": "A stabilizer linked to digestive issues and potential allergenic reactions.",
  "E111": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E573": "A stabilizer linked to Alzheimer’s disease and bone health issues.",
  "E465": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E215": "A preservative linked to allergic reactions and potential hormonal disruptions.",
  "E513": "A pH regulator that can cause severe digestive and respiratory tract irritation.",
  "E632": "A flavor enhancer linked to allergies, digestive issues, and potential gout flare-ups.",
  "E470aiii": "Anti-caking agents where processed salts may cause digestive issues and metabolic imbalances.",
  "E105": "A coloring agent that can cause digestive issues and potential allergic reactions.",
  "E446": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E479b": "Emulsifiers where processed fats may cause digestive issues and unhealthy weight gain.",
  "E960c": "Sweeteners linked to digestive issues and potential metabolic disturbances.",
  "E154": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E15x": "A food additive that can cause digestive issues and potential allergic reactions.",
  "E166": "A coloring agent linked to allergic reactions and potential carcinogenic effects.",
  "E232": "A preservative linked to potential carcinogenic effects and liver damage.",
  "E450vi": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E512": "A stabilizer linked to potential carcinogenic effects and digestive issues.",
  "E429": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E1451": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E580": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E121": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E1411": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E103": "A coloring agent linked to allergic reactions and potential carcinogenic effects.",
  "E424": "A thickener that can cause digestive issues like bloating and gas.",
  "E542": "A stabilizer derived from animal products that can cause digestive issues and potential allergenic reactions.",
  "E217": "A preservative linked to allergic reactions and potential hormonal disruptions.",
  "E283": "A preservative linked to allergic reactions, migraines, and potential gastrointestinal issues.",
  "E515i": "A stabilizer that may cause digestive issues and potassium overload.",
  "E308": "A synthetic antioxidant that can cause digestive issues and potential allergic reactions.",
  "E518": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E352i": "A stabilizer that may cause digestive issues and calcium overload.",
  "E304ii": "A synthetic antioxidant that can cause digestive issues and potential allergic reactions.",
  "E344": "An emulsifier derived from soy that can cause allergic reactions and digestive issues.",
  "E318": "A color fixative where excessive intake can lead to digestive discomfort and calcium overload.",
  "E540": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E170ii": "A stabilizer where high amounts can cause digestive discomfort and kidney stones.",
  "E367": "An acidity regulator that may cause digestive discomfort and throat irritation.",
  "E493": "An emulsifier that can cause digestive issues and potential allergenic reactions.",
  "E426": "A thickener derived from soy that can cause allergic reactions and digestive issues.",
  "E231": "A preservative linked to potential carcinogenic effects and liver damage.",
  "E923": "A dough conditioner linked to respiratory issues and potential carcinogenic effects.",
  "E427": "A thickener that can cause digestive issues like bloating and gas.",
  "E101a": "A food additive that can cause digestive issues and potential allergic reactions.",
  "E239": "A preservative linked to potential carcinogenic effects and kidney damage.",
  "E431": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E106": "A coloring agent where high doses can cause digestive issues and potential allergic reactions.",
  "E472g": "Emulsifiers that may cause digestive issues and unhealthy weight gain.",
  "E284": "A preservative linked to reproductive issues, digestive discomfort, and potential toxicity.",
  "E574": "An acidity regulator that may cause digestive issues and potential allergic reactions.",
  "E452iv": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E450iv": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E434": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E484": "An emulsifier that may cause digestive issues and unhealthy weight gain.",
  "E430": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E351": "A stabilizer that may cause digestive issues and potassium overload.",
  "E333ii": "A stabilizer that may cause digestive issues and calcium overload.",
  "E328": "A preservative that can cause digestive issues and potential allergic reactions.",
  "E314": "A flavoring agent that may cause digestive discomfort and potential allergic reactions.",
  "E560": "An anti-caking agent where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E312": "An antioxidant linked to potential carcinogenic effects and digestive issues.",
  "E240": "A preservative linked to potential carcinogenic effects and respiratory irritation.",
  "E910": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E160f": "A synthetic coloring agent that can cause lung issues and potential toxicity.",
  "E1413": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E1403": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E128": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E126": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E505": "A color fixative where excessive intake can lead to digestive discomfort and iron overload.",
  "E383": "A stabilizer that may cause digestive issues and calcium overload.",
  "E906": "A glazing agent linked to potential allergic reactions and digestive issues.",
  "E586": "A preservative linked to potential carcinogenic effects and skin irritation.",
  "E246": "Emulsifiers where processed fats may cause digestive issues and unhealthy weight gain.",
  "E628": "A flavor enhancer linked to allergies, digestive issues, and potential gout flare-ups.",
  "E496": "An emulsifier that can cause digestive issues and potential allergic reactions. de:Natürliche Quellkohlensäure: A carbonation agent that may cause digestive issues and gas build-up.",
  "E557": "An anti-caking agent where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E241": "A thickener that can cause digestive issues like bloating and gas.",
  "E408": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E399": "A stabilizer that may cause digestive issues and calcium overload. Inorganic salts: Mineral salts where excessive intake can cause digestive discomfort and mineral imbalances.",
  "E919": "A curing agent linked to potential carcinogenic effects and respiratory irritation.",
  "E571": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E322ii": "An emulsifier derived from soy that can cause allergic reactions and digestive issues.",
  "E907": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E182": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E345": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E354": "A stabilizer that may cause digestive issues and calcium overload.",
  "E366": "An acidity regulator that may cause digestive discomfort and throat irritation.",
  "E390": "A food additive that can cause digestive issues and potential allergic reactions.",
  "E488": "Emulsifiers where processed fats may cause digestive issues and unhealthy weight gain.",
  "E107": "A coloring agent linked to hyperactivity, allergic reactions, and potential carcinogenic effects.",
  "E478": "Emulsifiers where processed fats may cause digestive issues and unhealthy weight gain.",
  "E625": "A flavor enhancer linked to allergies, digestive issues, and potential neurotoxicity.",
  "E323": "An antioxidant that can cause digestive issues and potential allergic reactions.",
  "E467": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E313": "An antioxidant linked to potential carcinogenic effects and digestive issues.",
  "E642": "A flavor enhancer that can cause digestive issues and potential allergic reactions.",
  "E929": "A bleaching agent linked to potential carcinogenic effects and respiratory irritation.",
  "E388": "An antioxidant linked to potential carcinogenic effects and digestive issues.",
  "E1208": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E359": "A sequestrant that may cause digestive discomfort and acid-base imbalance.",
  "E938": "A propellant where excessive inhalation can cause respiratory issues and dizziness.",
  "E389": "A food additive that can cause digestive issues and potential allergic reactions.",
  "E486": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E472f": "Emulsifiers where processed fats may cause digestive issues and unhealthy weight gain.",
  "E623": "A flavor enhancer linked to allergies, digestive issues, and potential neurotoxicity.",
  "E640ii": "A flavor enhancer that may cause digestive issues and metabolic imbalances.",
  "E543": "A food additive that can cause digestive issues and potential allergic reactions.",
  "E335i": "An acidity regulator that may cause digestive issues and sodium overload.",
  "E213": "A preservative linked to allergic reactions, respiratory issues, and potential carcinogenic effects.",
  "E227": "A preservative linked to allergic reactions, respiratory issues, and potential carcinogenic effects.",
  "E545": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E922": "A dough conditioner linked to respiratory issues and potential carcinogenic effects.",
  "E384": "A sequestrant that can cause digestive issues and potential allergic reactions.",
  "E909": "A glazing agent derived from whale oil that can cause allergic reactions and digestive issues.",
  "E969": "A sweetener linked to potential carcinogenic effects and metabolic disturbances.",
  "E458": "A stabilizer linked to digestive issues and potential allergenic reactions.",
  "E489": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E633": "A flavor enhancer linked to allergies, digestive issues, and potential gout flare-ups.",
  "E1206": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E1205": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E483": "An emulsifier where processed fats may cause digestive issues and unhealthy weight gain.",
  "E538": "An anti-caking agent linked to potential cyanide toxicity and digestive issues.",
  "E440b": "A thickener where processed pectins may cause bloating and digestive discomfort.",
  "E537": "An anti-caking agent linked to potential cyanide toxicity and digestive issues.",
  "E912": "A glazing agent that may cause digestive issues and potential allergic reactions.",
  "E911": "An emulsifier where processed fats may cause digestive issues and unhealthy weight gain.",
  "E209": "A preservative linked to potential carcinogenic effects and hormonal disruptions.",
  "E473a": "Emulsifiers where processed fats may cause digestive issues and unhealthy weight gain.",
  "E335ii": "An acidity regulator that may cause digestive issues and sodium overload.",
  "E638": "A flavor enhancer that can cause digestive issues and potential allergic reactions.",
  "E349": "A stabilizer that may cause digestive discomfort and acid-base imbalance.",
  "E629": "A flavor enhancer linked to allergies, digestive issues, and potential gout flare-ups.",
  "E519": "A fortifying agent linked to potential toxicity and digestive issues.",
  "E357": "An acidity regulator that may cause digestive discomfort and acid-base imbalance.",
  "E926": "A bleaching agent linked to potential carcinogenic effects and respiratory irritation.",
  "E515ii": "A stabilizer that may cause digestive issues and potassium overload.",
  "E163c": "A coloring agent where processed malvidin can cause allergic reactions and digestive discomfort.",
  "E238": "A preservative linked to allergic reactions and potential DNA damage.",
  "E161c": "A coloring agent where high doses can cause digestive discomfort and potential toxicity.",
  "E546": "A stabilizer that may cause digestive issues and magnesium imbalance.",
  "E939": "A propellant where excessive inhalation can cause respiratory issues and dizziness.",
  "E452iii": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E553a": "Anti-caking agents where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E1517": "An emulsifier that can cause digestive issues and potential allergic reactions.",
  "E946": "A propellant linked to potential carcinogenic effects and respiratory irritation.",
  "E1441": "A thickener that can cause digestive issues and potential allergic reactions.",
  "E450viii": "A stabilizer that may cause kidney damage and disrupt calcium absorption, leading to bone health issues.",
  "E553aii": "An anti-caking agent where inhalation can cause respiratory issues; ingestion may lead to digestive discomfort.",
  "E495": "An emulsifier that can cause digestive issues and potential allergic reactions."
};

export default ADDITIVES;